### ISSUE TITLE
Import candle error with Binance

### ISSUE THREAD

**Issue by gianlup** [jesse-ai/jesse#78]
If I try to import candles with the command `jesse import-candles Binance BTCUSDT 2018-02-01` it starts to download but after some time the following exception is thrown `Uncaught Exception: CandleNotFoundInExchange: No candles exists in the market for this day: 2018-02-08 
Try another start_date
`

**Comment by firesurf** [comment]
Binance seems to have missing data there. You could use Bitfinex as an alternative candle source in this case or use a later start_date.

**Comment by gianlup** [comment]
Well yes, but there is this function https://github.com/jesse-ai/jesse/blob/b00f9fcc5b4e949d9935b3642b1fcd7860c1d0ff/jesse/modes/import_candles_mode/__init__.py#L256 that fills missing candles with the last price and volume 0. Why isn't applicable in this case?

**Comment by saleh-mir** [comment]
@gianlup if the exchange returns a number of candles, `_fill_absent_candles` checks for missing candles and fills them (using the candles around it). But in that period, no candle is received at all. So _fill_absent_candles can't do its job.

Basically Binance does not have candles for several days in that point. I have fixed this issue for Bitfinex and Coinbase by using a backup exchange to get the data for those days. But for Binance, I have not (yet)

**Comment by RonaldKepken** [comment]
Thanks for clarifying @saleh-mir!

I was wondering about this as well. I think it'd be a pretty important fix/improvement for Jesse.

**Comment by RonaldKepken** [comment]
Hey @saleh-mir 

This is actually not fixed for Binance right?

**Comment by saleh-mir** [comment]
@RonaldKepken there's not a lot we can do except maybe to use a backup exchange for Binance. IMO Binance should fix it. Or maybe we can hardcode a date for BTC on Binance that we know has the candles.
